export const countOfNotes = document.querySelector(".countOfNotes");
export const navBtnsNotesPage = document.querySelectorAll(".btn");
export const pages = document.querySelectorAll(".page");
export const allNotesPanel = document.querySelector(".allNotesPanel");
export const noteTitle = document.querySelector(".headingOfNote");
export const contentOfNote = document.querySelector(".contentOfNote");
export const btnNewNote = document.querySelector(".BtnNewLetter");
export const searchBar = document.querySelector(".searchBar");
// export let isNoteOpened;
export const btnDeleteNote = document.querySelector(".deleteNote");
